#!/bin/bash
#
# bash-exit-codes
# Brian Sorahan
#
# $1 - output file (default is /etc/bash.d/exitcodes)
#      /etc/bash.d will be created if it doesn't exist
# $2 - header file to scan (default is /usr/include/sysexits.h)

. conf

main() {
	local outfile=${1-"${OUTFILE}"}
	local infile=${2-"${INFILE}"}
	local bash_dir=`dirname ${outfile}`
	local uname_a=`uname -a`
	
	[ ! -d "${bash_dir}" ] && mkdir -p "${bash_dir}"

	cat <<PREAMBLE >"${outfile}"
# bash-exit-codes/${0##./} generated this file
# from ${infile} on
# ${uname_a}

PREAMBLE

	# captures: 1 2
	local exitcode_re='EX\([_[:alpha:]]*\)[[:space:]]*\([[:digit:]]*\)'
	#captures: 3
	local comment_re='\/\* \(.*\) \*\/'
	# sed's match pattern
	local define_re="#define ${exitcode_re}[[:space:]]*${comment_re}"

	sed -n "s/${define_re}/EX\1=\2 # \3/p" "${infile}" >>"${outfile}"
}

main "$@"